# Generated by Django 5.0.7 on 2024-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='Images/portfolio')),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
